{
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "vendor_name" : "IBM",
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "Security Guardium Data Encryption",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "3.0.0.2"
                              }
                           ]
                        }
                     }
                  ]
               }
            }
         ]
      }
   },
   "data_type" : "CVE",
   "impact" : {
      "cvssv3" : {
         "TM" : {
            "E" : "U",
            "RC" : "C",
            "RL" : "O"
         },
         "BM" : {
            "C" : "L",
            "AC" : "L",
            "SCORE" : "2.700",
            "AV" : "N",
            "I" : "N",
            "PR" : "H",
            "A" : "N",
            "UI" : "N",
            "S" : "U"
         }
      }
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "value" : "Obtain Information",
                  "lang" : "eng"
               }
            ]
         }
      ]
   },
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "IBM Security Guardium Data Encryption (GDE) 3.0.0.2 generates an error message that includes sensitive information about its environment, users, or associated data.  IBM X-Force ID:  171931."
         }
      ]
   },
   "data_version" : "4.0",
   "data_format" : "MITRE",
   "references" : {
      "reference_data" : [
         {
            "name" : "https://www.ibm.com/support/pages/node/6320835",
            "title" : "IBM Security Bulletin 6320835 (Security Guardium Data Encryption)",
            "refsource" : "CONFIRM",
            "url" : "https://www.ibm.com/support/pages/node/6320835"
         },
         {
            "url" : "https://exchange.xforce.ibmcloud.com/vulnerabilities/171931",
            "title" : "X-Force Vulnerability Report",
            "name" : "ibm-gde-cve20194699-info-disc (171931)",
            "refsource" : "XF"
         }
      ]
   },
   "CVE_data_meta" : {
      "DATE_PUBLIC" : "2020-08-24T00:00:00",
      "ID" : "CVE-2019-4699",
      "STATE" : "PUBLIC",
      "ASSIGNER" : "psirt@us.ibm.com"
   }
}
